/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ProdutoController;
import Model.CadastroProdutoModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class CadastroProdutoView extends javax.swing.JFrame {

    /**
     * Creates new form ProdutoView
     */
    int CodigoEdit = 0;
    boolean Editar = false;
    
    public CadastroProdutoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxNome = new javax.swing.JTextField();
        jlNome = new javax.swing.JLabel();
        jlDescricao = new javax.swing.JLabel();
        jlMarca = new javax.swing.JLabel();
        jtxMarca = new javax.swing.JTextField();
        jlCadProduto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaDescricao = new javax.swing.JTextArea();
        jlFornecedor = new javax.swing.JLabel();
        jtxFornecedor = new javax.swing.JTextField();
        jtxValorCompra = new javax.swing.JTextField();
        jlValorCompra = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jlValorVenda = new javax.swing.JLabel();
        jtxValorVenda = new javax.swing.JTextField();
        jbLimparCampos = new javax.swing.JButton();
        jtxValorLucro = new javax.swing.JTextField();
        jlValorLucro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxNomeActionPerformed(evt);
            }
        });

        jlNome.setText("Nome do Produto:");

        jlDescricao.setText("Descrição:");

        jlMarca.setText("Marca:");

        jlCadProduto.setText("Cadastro de Produtos");

        jtxaDescricao.setColumns(20);
        jtxaDescricao.setRows(5);
        jScrollPane1.setViewportView(jtxaDescricao);

        jlFornecedor.setText("Fornecedor:");

        jlValorCompra.setText("Valor de Compra:");

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jlValorVenda.setText("Valor de Venda:");

        jtxValorVenda.setEditable(false);

        jbLimparCampos.setText("Limpar Campos");
        jbLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparCamposActionPerformed(evt);
            }
        });

        jtxValorLucro.setEditable(false);

        jlValorLucro.setText("Valor de Lucro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlValorVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jlCadProduto))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlValorCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jbSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jbSair))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jlValorLucro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxValorLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbLimparCampos))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jlDescricao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlCadProduto)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDescricao)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMarca)
                    .addComponent(jtxMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFornecedor)
                    .addComponent(jtxFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValorCompra)
                    .addComponent(jtxValorCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValorVenda)
                    .addComponent(jtxValorVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValorLucro)
                    .addComponent(jtxValorLucro)
                    .addComponent(jbLimparCampos))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbSair))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxNomeActionPerformed

    private void jbLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparCamposActionPerformed
        // TODO add your handling code here:
        jtxNome.setText("");
        jtxaDescricao.setText("");
        jtxFornecedor.setText("");
        jtxMarca.setText("");
        jtxValorCompra.setText("");
        jtxValorLucro.setText("");
        jtxValorVenda.setText("");
    }//GEN-LAST:event_jbLimparCamposActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Se você sair irá perder todos os dados informados, deseja continuar?")==0){
            dispose();
            ProdutoView produto = new ProdutoView();
            produto.setVisible(true);
        }
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // TODO add your handling code here:
        if (!Editar){
            if((!jtxNome.getText().trim().equals("")) && (!jtxValorCompra.getText().trim().equals(""))){
                CadastroProdutoModel produto = new CadastroProdutoModel();
                produto.setNome(jtxNome.getText());
                produto.setDescricao(jtxaDescricao.getText());
                produto.setFornecedor(jtxFornecedor.getText());
                produto.setMarca(jtxMarca.getText());
                produto.setValorCompra(Float.parseFloat(jtxValorCompra.getText()));
                
                ProdutoController controle = new ProdutoController();
                if(controle.inserirProduto(produto)){
                    JOptionPane.showMessageDialog(this, "Aluno Cadastrado com sucesso!");
                    jbLimparCamposActionPerformed(evt);
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao Cadastrar Produto!", 
                            "Retorno", JOptionPane.ERROR_MESSAGE);
                }
           }else{
                JOptionPane.showMessageDialog(this, "Erro ao Cadastrar Produto! Campos obrigatorios Incompletos", 
                            "Retorno", JOptionPane.ERROR_MESSAGE);
           }
        }else{
            if((!jtxNome.getText().trim().equals("")) && (!jtxValorCompra.getText().trim().equals(""))){
                CadastroProdutoModel produto = new CadastroProdutoModel();
                produto.setCodigo(CodigoEdit);
                produto.setNome(jtxNome.getText());
                produto.setDescricao(jtxaDescricao.getText());
                produto.setFornecedor(jtxFornecedor.getText());
                produto.setMarca(jtxMarca.getText());
                produto.setValorCompra(Float.parseFloat(jtxValorCompra.getText()));
                ProdutoController controle = new ProdutoController();
                if(controle.editarProduto(produto)){
                    JOptionPane.showMessageDialog(this, "Aluno Editado com sucesso!");
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao Editar Aluno!", 
                            "Retorno", JOptionPane.ERROR_MESSAGE);
                }       
           }else{
                JOptionPane.showMessageDialog(this, "Erro ao Cadastrar Aluno! Campos Incompletos", 
                            "Retorno", JOptionPane.ERROR_MESSAGE);
            }
            dispose();
            ProdutoView produto = new ProdutoView();
            produto.setVisible(true);
            Editar = false;
            CodigoEdit = 0;
        }
    }//GEN-LAST:event_jbSalvarActionPerformed
    
    
    void recebeDados(int CodigoAluno, boolean EditarProduto){
        CodigoEdit = CodigoAluno;
        Editar = EditarProduto;
        CadastroProdutoModel produto = new CadastroProdutoModel();
        produto.setCodigo(CodigoEdit);
        ProdutoController controle = new ProdutoController();
        produto = controle.selecionarProduto(produto);
        if(produto != null){
            jtxNome.setText(produto.getNome());
            jtxaDescricao.setText(produto.getDescricao());
            jtxFornecedor.setText(produto.getFornecedor());
            jtxMarca.setText(produto.getMarca());
            jtxValorCompra.setText(String.valueOf(produto.getValorCompra()));
            jtxValorLucro.setText(String.valueOf(produto.getValorLucro()));
            jtxValorVenda.setText(String.valueOf(produto.getValorVenda()));
        }else{
            JOptionPane.showMessageDialog(this, "Produto não encontrado!", 
                        "Retorno", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbLimparCampos;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlCadProduto;
    private javax.swing.JLabel jlDescricao;
    private javax.swing.JLabel jlFornecedor;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlValorCompra;
    private javax.swing.JLabel jlValorLucro;
    private javax.swing.JLabel jlValorVenda;
    private javax.swing.JTextField jtxFornecedor;
    private javax.swing.JTextField jtxMarca;
    private javax.swing.JTextField jtxNome;
    private javax.swing.JTextField jtxValorCompra;
    private javax.swing.JTextField jtxValorLucro;
    private javax.swing.JTextField jtxValorVenda;
    private javax.swing.JTextArea jtxaDescricao;
    // End of variables declaration//GEN-END:variables
}
